# Generated by Django 5.0.6 on 2024-06-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Сырок без названия', max_length=50, verbose_name='Название')),
                ('anons', models.CharField(default='Сырок без краткого описания', max_length=255, verbose_name='Краткое описание')),
                ('description', models.TextField(default='Сырок без описания', verbose_name='Описание')),
                ('Цена неизвестна', models.IntegerField(verbose_name='Цена')),
            ],
        ),
    ]
