# Generated by Django 5.0.6 on 2024-06-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='products',
            name='manufacturer',
            field=models.CharField(default='Неизвестный производитель', max_length=255, verbose_name='Производитель'),
        ),
    ]
