# Generated by Django 5.0.6 on 2024-06-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_options_products_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Цена неизвестна',
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
